dimensions/YAxis: correct label/title rotation for computing Y-axis width
apexcharts/apexcharts.js pull request #2260
Opened 2021-02-26 02:28 UTC by karna48

# YAxis width corrected
Using multiple Y-axis (6) there were visible problems with spaces between them.
yaxis[i].labels.rotate and yaxis[i].title.rotate were not properly used when computing the bounding boxes

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-02-26 02:33 UTC, karna48 reviewed
I have run the tests and all passes.
Visually multiple Y-axis (more than 1 on one side) looks cleaner

2021-03-08 12:24 UTC, junedchhipa requested changes
Please fix the 2 issues I mentioned.
Rest looks good.

2021-03-08 12:24 UTC, junedchhipa commented on src/modules/dimensions/YAxis.js
> +          yaxe.title.style.fontFamily,
It should be `yaxe.labels.style.fontFamily`

2021-03-08 12:24 UTC, junedchhipa commented on src/modules/dimensions/YAxis.js
> +            yaxe.title.style.fontFamily,
It should be `yaxe.labels.style.fontFamily`

2021-03-15 19:01 UTC, junedchhipa approved these changes

2021-03-15 19:01 UTC, merged